# Generated by Django 5.2.7 on 2025-11-02 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('instansi', models.CharField(blank=True, max_length=200, null=True)),
                ('keperluan', models.TextField()),
                ('tanggal_waktu', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Absensi Tamu',
                'verbose_name_plural': 'Data Absensi Tamu',
                'ordering': ['-tanggal_waktu'],
            },
        ),
    ]
