# Generated by Django 5.2.4 on 2025-12-12 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0003_make_contact_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensitamu',
            name='alamat',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='absensitamu',
            name='instansi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='absensitamu',
            name='nomor_telepon',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor telepon harus berupa angka maks. 15 digit', regex='^\\d{0,15}$')]),
        ),
    ]
